namespace AuditSystem.Application.Features.Reports.InternalAuditConsolidationReport.Create;

public sealed record class CreateInternalAuditConsolidationReportCommandResponse(Guid InternalAuditConsolidationId);